baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Notebook"
theme = "no-js-hugo-theme"

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = false

  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6

[params]
  # enable javascript theme switcher
  # default: false
  themeStyleSwitcher = true

  # theme style if the theme switcher is disabled
  # default: "light.css"
  #themeStyle = "dark.css"

  # footer markdown text at the bottom of every page
  # default: <unset>
  footerText = "[no-js-hugo-theme](https://github.com/stevenengler/no-js-hugo-theme)"

  # enable the table of content on pages with more than this many words (negative to disable)
  # (can be overridden per-page by setting the 'toc' front matter parameter)
  # default: <unset>
  #tocWordThreshold = 1000

  # adds an "onion-location" meta attribute to the HTML of each page
  # default <unset>
  #onionLocation = "http://<your-onion-service-address>.onion"
